### ISSUE TITLE
Slash in the code?

### ISSUE THREAD

**Issue by tomekwi** [jgorset/git.io#2]
Hi, I’ve just tried this:

```sh
$ git.io https://github.com/tomekwi/elm-live/issues --code=elm-live/issues
http://git.io/elm-live/issues

$ echo $?
0
```

But this looks broken: http://git.io/elm-live/issues. Are slashes allowed?

One of these options would be great:
* Slashes are allowed
* Slashes are rewritten. I. e. whenever I register *http://git.io/elm-live → https://github.com/tomekwi/elm-live*, http://git.io/elm-live/whatever will implicitly point at https://github.com/tomekwi/elm-live/whatever.

**Comment by jgorset** [comment]
Hi @tomekwi! This gem is just a simple wrapper for GitHub's git.io service, and it seems that it doesn't work well with slashes (you'll notice that it returns a 404). It would be cool if it supported either of the options you describe, but since I don't work for GitHub I can't really make it happen. I wonder who we might ping who could, though…

**Comment by jgorset** [comment]
what about @technoweenie or @atmos? :pray:

**Comment by tomekwi** [comment]
Hi, thanks for the response!

I did have a feeling that git.io is only a delicious wrapper. (I remember having to `curl` https://git.io before I learnt about your fantastic tool!)

> This gem is just a simple wrapper for GitHub's git.io service

I posted the issue here because the little
![image](https://cloud.githubusercontent.com/assets/4624660/11179323/dbedcbcc-8c52-11e5-821c-ab976d22723d.png) icon at the bottom points at https://github.com. I was sure this was a bug!

Fair enough – I’ll post an email to github – perhaps they’ll respond. It would be cool, but it’s nothing super important.

> you'll notice that it returns a 404 without redirecting

Does the API return a 404 or https://git.io/elm-live/issues? If it’s the API, perhaps `git.io` could print a warning and fail?

**Comment by technoweenie** [comment]
Codes don't allow slashes. It's highly unlikely we'll be introducing this to git.io. Feel free to use dashes though.

**Comment by tomekwi** [comment]
Thanks for the info @technoweenie. Is it likely that you’ll rewrite slashes? So if `git.io/a` points at `b.com`, `git.io/a/c` would implicitly redirect to `b.com/c`?

**Comment by technoweenie** [comment]
Nope, git.io is in maintenance mode.

**Comment by jgorset** [comment]
Ya'll should open source it, @technoweenie. :wink:

**Comment by technoweenie** [comment]
@jgorset It already is: https://github.com/technoweenie/guillotine. Feel free to take it and setup your own url shortener :)

**Comment by jgorset** [comment]
Ha, well, nice!
